fixes:
  - "src/::"
coverage:
  status:
    project:
      default:
        flags:
          - nodl_python
          - ros2nodl
      nodl_python:
        flags:
          - nodl_python
      ros2nodl:
        flags:
          - ros2nodl
flags:
  nodl_python:
    paths:
      - nodl_python
  ros2nodl:
    paths:
      - ros2nodl

